---
# Browsers to include [brave|chrome|tor]
browsers:
  - chrome
  - brave
  - tor

# Chrome
chrome_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Brave
brave_repo_url: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
brave_apt_url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
brave_apt_keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg

# Tor
tor_apt_url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
tor_apt_repo: "deb https://deb.torproject.org/torproject.org/ {{ ansible_distribution_release }} main"
tor_keyring: /etc/apt/trusted.gpg.d/torproject.gpg
