---
prereq_pkgs: [ca-certificates, curl, apt-transport-https, lsb-release, gnupg, bash-completion, gnupg2, curl, software-properties-common, virtualenv, python3-setuptools, unzip, libxtst6, libx11-xcb1, libxcb-dri3-0, libasound2, libssl-dev]
kubectx: yes
kubectx_dir: "/home/{{ ansible_user }}/.kubectx"
#git
git_user: "test"
git_email: "test@test.com"
#terrafrom
terraform_version: 0.12.25
terraform_zip: "terraform_{{ terraform_version}}_linux_amd64.zip"
terraform_download_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_zip }}"
molecule_remote_src: yes
#vs_code
install_extensions: no
code_extensions: [eamodio.gitlens, hashicorp.terraform, ivory-lab.jenkinsfile-support, ms-azuretools.vscode-docker, ms-kubernetes-tools.vscode-kubernetes-tools, ms-python.python, redhat.vscode-yaml]
running_on_molecule: no
user_data_dir: ""
#docker
include_compose: yes
compose_version: 1.25.5
