---
all:
  hosts:
    # 52.56.102.37:
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: /ssh//key/path/ssh_key.pem
    localhost:
      ansible_connection: local

home_group:
  hosts:
    localhost:
