---
# -------------------------------------------------------------------------#
# ------------------------Slack--------------------------------------------#
- name: apt-get update
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install gdebi
  become: true
  ansible.builtin.apt:
    name: gdebi
    state: present

- name: Check if slack is installed
  ansible.builtin.command: dpkg-query -W slack-desktop
  register: check_slack
  failed_when: false
  changed_when: false

- name: Download Ubuntu slack package
  become: true
  ansible.builtin.command: "{{ slack_package }}"
  args:
    creates: "{{ temp_dir }}/slack-desktop-{{ slack_version }}-amd64.deb"
  when: check_slack.rc == 1
  retries: 3
  delay: 5

- name: Install Slack
  become: true
  ansible.builtin.apt:
    deb: "{{ temp_dir }}/slack-desktop-{{ slack_version }}-amd64.deb"
    state: present
  when: check_slack.rc == 1

# -------------------------------------------------------------------------#
# ------------------------Zoom---------------------------------------------#

- name: Download Zoom package
  become: true
  ansible.builtin.get_url:
    url: "https://zoom.us/client/latest/zoom_amd64.deb"
    dest: "{{ temp_dir }}/zoom_amd64.deb"
    timeout: 30
  retries: 3
  delay: 5

- name: Install zoom
  become: true
  ansible.builtin.apt:
    deb: "{{ temp_dir }}/zoom_amd64.deb"
    state: present

# --------------------------------------------------------------------------#
# ------------------------Telegram------------------------------------------#

- name: Add Telegram repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:atareao/telegram'

- name: Install Telegram
  become: true
  ansible.builtin.package:
    name: telegram
    state: present
...
