---
- name: Install pre-requisites
  become: true
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Install Slack
  become: true
  apt: deb=http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb

- name: Install zoom
  become: true
  apt: deb=https://zoom.us/client/latest/zoom_amd64.deb

- name: Add Telegram repository
  become: true
  apt_repository: repo='ppa:atareao/telegram'

- name: Install Telegram
  become: true
  package: name=telegram

  #-------------------------------------------------------#
  #------------------------Lens-------------------------#

- name: Get the Lens Desktop public security key
  become: true
  command: curl -fsSL https://downloads.k8slens.dev/keys/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/lens-archive-keyring.gpg > /dev/null

- name: Add the Lens Desktop repo
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/lens.list
    line: "deb [arch=amd64 signed-by=/usr/share/keyrings/lens-archive-keyring.gpg] https://downloads.k8slens.dev/apt/debian stable main"
    create: yes

- name: Specify the stable channel
  become: true
  file:
    path: /etc/apt/preferences.d/lens
    state: touch
    mode: '0644'
  lineinfile:
    path: /etc/apt/preferences.d/lens
    line: |
      Package: *
      Pin: release a=stable
      Pin-Priority: 800

- name: Install or update Lens Desktop
  become: true
  apt:
    update_cache: yes
    name: lens
    state: present
