---
#--------------------------------------------------#
#--------------azure_cli-----------------------------#

- name: Install Pre-requisite Packages
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Add an Apt signing key for Az CLI
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/microsoft.asc.gpg

- name: Add azure cli repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main"
    filename: azure-cli

- name: Install azure cli
  become: true
  apt:
    name: azure-cli
    update_cache: yes

#--------------------------------------------------#
#--------------aws_cli-----------------------------#

- name: Update the server
  become: true
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes

- name: Install Pre-requisite Packages
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present

- name: Uninstall AWS CLI V1
  ansible.builtin.apt:
    name: awscli
    state: absent

- name: Delete the old AWS CLI V2 temp files
  ansible.builtin.file:
    path: /tmp/aws
    state: absent

- name: Download and unzip the AWS CLI V2
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: Run the AWS CLI V2 installer
  become: true
  shell: "/tmp/aws/install --update"


#--------------------------------------------------#
#--------------kubectl-----------------------------#

- name: Install Pre-requisite Packages
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present

- name: Add kubectl apt key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/kubectl-apt-key.gpg

- name: Add kubectl repo
  become: true
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install kubectl
  become: true
  apt:
    name: kubectl
    state: present
    update_cache: yes

- name: Create kubectl dir
  become: yes
  file:
    state: directory
    path: "/home/{{ ansible_user }}/.kube"
    mode: '0744'

- name: Create kubeconfig file
  become: true
  copy:
    content: ""
    dest: "/home/{{ ansible_user }}/.kube/config"
    force: yes
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Ensure autocompletion dirs exist.
  file:
    path: /etc/bash_completion.d
    recurse: no
    state: directory
    mode: '0755'

- name: Enable kubectl auto completion
  become: true
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  changed_when: false

- include: kubectx.yaml
  when: kubectx

#---------------------------------------------------#
#--------------------helm---------------------------#

- name: Add helm apt key
  become: true
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

- name: Add helm repo
  become: true
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main

- name: Install helm
  become: true
  apt:
    name: helm
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create bash_completion.d dir
  file:
    name: /etc/bash_completion.d
    state: directory
    mode: '0755'

- name: Helm Completion
  become: true
  shell: helm completion bash > /etc/bash_completion.d/helm
  changed_when: false

  #-------------------------------------------------------#
  #------------------------docker-------------------------#

- name: Update apt
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add Docker GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Update apt
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  #-----docker-compose-----#

- name: Download docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    timeout: 30

- name: Make Executable
  become: true
  file:
    path: /usr/local/bin/docker-compose
    mode: +x

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add User to Docker Group
  become: true
  user:
    append: yes
    groups: docker
    name: "{{ ansible_user_id }}"

- name: Debug system restart
  debug:
    msg: Restart system for group changes to take affect

  #-------------------------------------------------------#
  #------------------------terraform-------------------------#

- name: Install Pre-requisites
  become: true
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Check Terraform executable exists.
  stat:
    path: /usr/local/bin/terraform
  register: stat_terraform

- name: Download Terraform
  get_url:
    url: "{{ terraform_download_url }}"
    dest: "/var/tmp/{{ terraform_zip }}"
  when: not stat_terraform.stat.exists

- name: Extract terraform into /usr/local/bin
  become: true
  unarchive:
    src: "/var/tmp/{{ terraform_zip }}"
    dest: /usr/local/bin/
    remote_src: "{{ molecule_remote_src }}"
  when: not stat_terraform.stat.exists

- name: Remove downloaded zip
  become: true
  file:
    path: "/var/tmp/{{ terraform_zip }}"
    state: absent
  when: not stat_terraform.stat.exists

  #-------------------------------------------------------#
  #------------------------vs_code-------------------------#

- name: Install Code Extensions
  become: no
  command: "/usr/bin/code --install-extension {{ item }} {{ user_data_dir }}"
  loop: "{{ code_extensions }}"
  changed_when: false

- name: Install pre-requisites
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Install VS Code
  become: true
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add VisualStudio Code apt keys
  become: true
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc
- name: Add VisualStudio Code repository
  become: true
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
- name: Install VisualStudio Code
  become: true
  package: name=code

  #-------------------------------------------------------#
  #------------------------virtual_env-------------------------#

- name: Install apt pre-requisites
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Create molecule virtualenv dir
  file:
    path: ~/.virtualenvs/molecule
    state: directory
    mode: "0755"

- name: Copy requirements
  copy:
    src: requirements.txt
    dest: /var/tmp/requirements.txt
    mode: '0644'

- name: Install requirements in virtualenv
  pip:
    requirements: /var/tmp/requirements.txt
    virtualenv_python: python3
    virtualenv: ~/.virtualenvs/molecule

  #-------------------------------------------------------#
  #------------------------git-------------------------#

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes

- name: Create user dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}
    state: directory

- name: Copy git config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    mode: 0640
