---
- name: Install Pre-requisite Packages
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Download AWS CLI bundle
  get_url:
    url: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
    dest: /tmp/awscli-bundle.zip

- name: Install unzip
  become: true
  apt:
    name: unzip
    state: present

- name: Unzip AWS CLI bundle
  ansible.builtin.unarchive:
    src: /tmp/awscli-bundle.zip
    dest: /tmp

- name: Install AWS CLI
  become: true
  command: /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

