---
- hosts: all
  vars_files:
    - /home/vaibhav/workspace/INTERNAL-PROJECTS/ubuntu-setup/inventories/vars.yml
  roles:
    - role: devops
      tags:
        - devops-tools

    - role: browsers
      tags:
        - web-browsers

    - role: communication-tools
      tags:
        - communication-tools

    - role: system-coniguration
      tags:
        - system-coniguration-tools
...