---
- hosts: all
  vars_files:
    - /home/vaibhav/workspace/INTERNAL-PROJECTS/ubuntu-setup/inventory/host_vars/localhost.yaml
  roles:

    - role: debug
      tags: debug

    - role: common
      tags:
        - devops

    - role: browsers
      tags:
        - web

    - role: terminal-shell-configuration

    - role: communication

    - role: system_configuration